"""baseline schema

Revision ID: 472f4aebe540
Revises: 
Create Date: 2025-11-11 10:09:09.251810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472f4aebe540'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('detected_sport', sa.String(length=50), nullable=True),
    sa.Column('grok_context', sa.Text(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_logs_id'), ['id'], unique=False)

    op.create_table('game_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('home_team', sa.String(), nullable=True),
    sa.Column('away_team', sa.String(), nullable=True),
    sa.Column('bookmaker', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('odds_data', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_odds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_odds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_odds_sport'), ['sport'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('wager_amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_team_name'), ['team_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bets_user_id'))
        batch_op.drop_index(batch_op.f('ix_bets_team_name'))
        batch_op.drop_index(batch_op.f('ix_bets_id'))

    op.drop_table('bets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('game_odds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_odds_sport'))
        batch_op.drop_index(batch_op.f('ix_game_odds_id'))

    op.drop_table('game_odds')
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_logs_id'))

    op.drop_table('ai_logs')
    # ### end Alembic commands ###
