"""add ai_logs table

Revision ID: 67fd911638c2
Revises: f61892921d14
Create Date: 2025-11-11 07:40:58.398470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fd911638c2'
down_revision: Union[str, Sequence[str], None] = 'f61892921d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bets_id'))
        batch_op.drop_index(batch_op.f('ix_bets_team_name'))
        batch_op.drop_index(batch_op.f('ix_bets_user_id'))

    op.drop_table('bets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)

    op.create_table('bets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team_name', sa.VARCHAR(), nullable=False),
    sa.Column('odds', sa.FLOAT(), nullable=False),
    sa.Column('wager_amount', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bets_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_team_name'), ['team_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_id'), ['id'], unique=False)

    # ### end Alembic commands ###
